config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :players
    resources :territories

    root to: "players#index"
  end

  root 'static_pages#home'

  # Redirect default behaviour to show gamepage view instead.
  get '/players/:id', to: redirect('/gamepage/%{id}')
  # Show action defines @player which can be used to access attributes.
  get '/gamepage/:id', to: 'gamepage#show'

  get '/register', to: 'players#new'
  post '/register', to: 'players#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'

  get '/players', to: 'players#list'

  put '/players/achievement_create/:id', to: 'territories#create'
  get 'territories/get/:id', to: 'territories#territories_in_view'
  put '/territories/invade/:id', to: 'territories#invade'
  put '/territories/expand', to: 'territories#expand'

  mount ActionCable.server, at: '/cable'




  resources :players









  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  include SessionsHelper

  def help
  end

  def about
  end

  def home
    @player = current_player
    if @player
      redirect_to ('/gamepage/'+ @player.id.to_s)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div id="about-page" class="home-container">
  <%= render 'layouts/header'%>
  <%= render 'layouts/side_nav'%>
  <div class="static-content">
    <h1 style="margin-top:0">About</h1>
    <p>Agile: Run for your kingdom was developed as part of a team project for the course CMPT 276 at SFU. </p>
    <button id="more-about" class="waves-effect waves-light btn-large" type="button" name="more-about">More</button>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "About") %>
<div id="help-page" class="home-container">
  <%= render 'layouts/header'%>
  <%= render 'layouts/side_nav'%>
  <div class="static-content">
    <h1 style="margin-top:0;">Help</h1>
    <p>The following button will launch a first-time tour to get you started!</p>
    <a class="tour-help waves-effect waves-light btn-large" href="">
      <i class="material-icons left">ac_unit</i> Begin!
    </a>
  </div>
</div>

app/views/static_pages/home.html.erb

<div id="logo-container" style="opacity:1">
  <center>
    <div id="logo-content">
      <div id="logo"></div>
      <h4 id="tagline"> Run For Your Kingdom </h4>
    </div>
    <button class="logo-exit waves-effect btn" data-activates="logo-exit">Click To Continue</button>
  </center>
</div>
<div class="home-container">

  <%= render "layouts/header" %>
  <%= render "layouts/side_nav" %>

  <% if !@player %>
  <div class="log-sign-btn-cont">
    <a class="login-btn waves-effect" href="#login-block" data-activates='forms-container'>
      Login
    </a>
    <a class="register-btn waves-effect" href="#register-block" data-activates='forms-container'>
      Register
    </a>
  </div>
  <% end %>

  <div id="homepage-map" class="map"></div>
  <% if logged_in? %>
    <%= render "layouts/dashboard" %>
    <%= render "layouts/leaderboard" %>
  <% end %>
  <div class="forms-container">
    <div class="form-tabs row">
      <div class="col s12" style="padding:0;">
        <ul class="tabs indigo">
          <li class="tab col s6">
            <a id="login-tab" class="white-text" href="#login-block" style="font-size:30px;">login</a>
          </li>
          <li class="tab col s6">
              <a id="register-tab" class="white-text" href="#register-block" style="font-size:30px;">register</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="form-blocks row valign-wrapper">
      <div id="login-block" class="col s12">
        <div class="form-content row">
          <%= form_for(:session, url: login_path, html: {id: "login-form"}) do |f| %>
          <div class="row">
            <div class="input-field col s12">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'validate black-text', id: 'login-email' %>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'validate black-text', id: 'login-password' %>
            </div>
          </div>
          <center>
            <div class="row">
              <%= f.submit "Log in", class: "form-submit white-text btn waves-effect waves-light" %>
            </div>

            <div class="row">
              <a class="blue-grey-text text-darken-4" href="">Forgot Password?</a>
            </div>
          </center>
        <% end %>
      </div>
    </div>
    <div id="register-block" class="col s12">
      <div class="form-content row">
        <%= form_for(:player, url: register_path, html: {id: "register-form"}) do |f| %>
        <div class="row">
          <div class="input-field col s6">
            <%= f.label :first_name, 'First Name' %>
            <%= f.text_field :first_name, class: 'validate black-text' %>
          </div>
          <div class="input-field col s6">
            <%= f.label :last_name, 'Last Name' %>
            <%= f.text_field :last_name, class: 'validate black-text' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.label :email %>
            <%= f.email_field :email , class: 'validate black-text', id: 'register-email' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.label :username %>
            <%= f.text_field :username, class: 'validate black-text' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'validate black-text', id: 'register-password' %>
          </div>
          <div class="input-field col s6">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'validate black-text' %>
          </div>
        </div>
        <center>
          <div class="row">
            <%= f.submit "Register", class: "form-submit white-text waves-effect waves-light" %>
          </div>
        </center>
      <% end %>
    </div>
  </div>
    </div>
    <center>
        <button class="forms-exit waves-effect waves-light btn-large" data-activates="forms-exit">
          <i class="material-icons" style="font-size:70px;">arrow_drop_up_circle</i>
        </button>
    </center>
  </div>
</div>

<!-- <script>
TweenMax.staggerFrom("h1", 0.5, { opacity:0, y:0, delay:0.5, ease:Bounce.easeOut},0.2);

</script> -->
<!--<script id='map-script' src='https://maps.googleapis.com/maps/api/js?key=AIzaSyBabM1G2ohtxRzaaDP4tyDfd9aubA1CXg8&callback=init' async defer></script>-->