config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :players
    resources :territories

    root to: "players#index"
  end

  root 'static_pages#home'

  # Redirect default behaviour to show gamepage view instead.
  get '/players/:id', to: redirect('/gamepage/%{id}')
  # Show action defines @player which can be used to access attributes.
  get '/gamepage/:id', to: 'gamepage#show'

  get '/register', to: 'players#new'
  post '/register', to: 'players#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'

  get '/players', to: 'players#list'

  put '/players/achievement_create/:id', to: 'territories#create'
  get 'territories/get/:id', to: 'territories#territories_in_view'
  put '/territories/invade/:id', to: 'territories#invade'
  put '/territories/expand', to: 'territories#expand'

  mount ActionCable.server, at: '/cable'




  resources :players









  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_dashboard.html.erb
<div id="dashboard" style="display: none;">
    <button id="dashboard-exit" class="btn waves-effect waves-light" data-activates="dashboard-exit">
      <i class="material-icons">close</i>
    </button>
    <h1 class="dashboard-content"><%=@player.username%></h1>
    <h4 class="dashboard-content"> Score: <%=@player.score%></h4>
    <h4 class="dashboard-content"> Ranking: </br>
      <h5 class="dashboard-content">    Globally: <%=@player.rank%> </br>
      <h5 class="dashboard-content">    Nationally: <%=@player.rank%></br>
      <h5 class="dashboard-content">    Locally: <%=@player.rank%></br>
    </h4>
    <h4 class="dashboard-content"> Last Territory Update at: <%=@player.updated_at.to_formatted_s(:short) %></h4>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div class="nav-wrapper">
      <% if @player %>
        <a class="username">Welcome,
          <%= @player.first_name %>!</a>
      <% end %>
      <ul class="right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <% if @player %>
          <li>
            <a class="dashboard-trigger" data-activates="dashboard">
              Dashboard
            </a>
          </li>
          <!-- Account Dropdown Structure -->

          <li>
            <a class='account-link dropdown-button' href='' data-activates='header-account-dropdown'>
              <i class="material-icons left">account_circle</i>Account
            </a>
            <ul id='header-account-dropdown' class='dropdown-content'>
              <li>
                <a href="#!">Profile</a>
              </li>
              <li>
                <a href="#!">Settings</a>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to logout_path, :method => :delete do %>
                  <i class="material-icons left">backspace</i>Logout
              <% end %>
            </li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
</header>

app/views/layouts/_leaderboard.html.erb
<!-- Side bar -->
<div id = "left-bar">

</div>

    <!-- Slide out nav bar -->
    <div id="slide-out">

      <h4 style="font-weight: bold; margin-left: 15px;">Leaderboard</h4>

      <% @players = Player.all
          @players = @players.sort_by { |obj| obj.score }
          @players = @players.reverse
          @players.each do |elem|
      %>
      <p class='leaderboard-players'> <strong><%= elem.rank %>.</strong> <%= elem.username %> : <%= elem.score %> </p>

      <%end%>
    </div>

    <!-- Slide down button -->
    <div id = "slide-down-circle">
    <div id = "slide-down-arrow">
    </div>
    </div>

    <!-- Button to pull out nav -->
    <div id="click-toggle-circle">

    <div id ="click-toggle-arrow">
    </div>

</div>

app/views/layouts/_side_nav.html.erb
<div id="sidenav-trigger" class="waves-effect waves-light" data-activates="side-nav"><i class="material-icons">menu</i></div>

<nav id="side-nav" style="display:none">
  <ul>
    <li class="waves-effect"><%= link_to 'Home', root_path %></li>
    <li class="waves-effect"><%= link_to 'Help', help_path %></li>
    <li class="waves-effect"><%= link_to 'About', about_path %></li>
    <% if @player %>
      <li class="waves-effect">
        <a class="dashboard-trigger" data-activates="dashboard">
          Dashboard
        </a>
      </li>

      <!-- Account Dropdown Structure -->

      <li>
        <a class='account-link dropdown-button' data-activates='sidenav-account-dropdown'>
          <i class="material-icons left">account_circle</i>Account
        </a>
        <ul id='sidenav-account-dropdown' class='dropdown-content'>
          <li>
            <a href="#!">Profile</a>
          </li>
          <li>
            <a href="#!">Settings</a>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to logout_path, :method => :delete do %>
              <i class="material-icons left">backspace</i>Logout
          <% end %>
        </li>
      </ul>
    </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>